# Generated by Django 3.2.1 on 2021-09-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
