# Generated by Django 3.1.7 on 2021-02-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210227_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('github', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('main_link', models.CharField(blank=True, max_length=300, null=True)),
                ('twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('vk', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'user_contacts',
                'verbose_name_plural': 'user_contacts',
                'db_table': 'user_contacts',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.ImageField(default=None, upload_to='photos/small', verbose_name='small photo')),
                ('large', models.ImageField(default=None, upload_to='photos/large', verbose_name='large photo')),
            ],
            options={
                'verbose_name': 'profile_photos',
                'verbose_name_plural': 'profile_photos',
                'db_table': 'profile_photos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('looking_for_a_job', models.BooleanField(default=False)),
                ('looking_for_a_job_description', models.TextField(default=None)),
                ('fullname', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, default=None, max_length=300)),
                ('about_me', models.TextField(default=None)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.contacts')),
                ('photos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.photos')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
            },
        ),
    ]
