# Generated by Django 3.2.1 on 2021-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'profile avatar',
                'verbose_name_plural': 'profiles avatars',
                'db_table': 'profiles_avatars',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'profile banner',
                'verbose_name_plural': 'profiles banners',
                'db_table': 'profiles_banners',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('main_link', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('vk', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'user contacts',
                'verbose_name_plural': 'users contacts',
                'db_table': 'users_contacts',
            },
        ),
    ]
