# Generated by Django 3.2 on 2021-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210404_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.URLField(default=None, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
