# Generated by Django 3.2.3 on 2021-05-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210408_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'profile photo', 'verbose_name_plural': 'profiles photos'},
        ),
        migrations.AlterModelTable(
            name='contacts',
            table='users_contacts',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='profiles_photos',
        ),
    ]
