# Generated by Django 3.2.3 on 2021-05-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210517_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile preferences',
                'verbose_name_plural': 'profiles preferences',
                'db_table': 'profiles_preferences',
            },
        ),
    ]
