# Generated by Django 3.2.3 on 2021-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profilepreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='looking_for_a_job',
            new_name='is_looking_for_a_job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='looking_for_a_job_description',
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
