# Generated by Django 3.2.3 on 2021-07-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210701_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=250)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile preferences',
                'verbose_name_plural': 'profiles preferences',
                'db_table': 'profiles_preferences',
            },
        ),
        migrations.DeleteModel(
            name='ProfilePreferences',
        ),
    ]
