# Generated by Django 3.2.3 on 2021-07-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210701_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.URLField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
    ]
