# Generated by Django 3.2.1 on 2021-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.SlugField(unique=True),
        ),
    ]
