# Generated by Django 3.2.3 on 2021-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
