# Generated by Django 3.2.1 on 2021-09-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'verification code', 'verbose_name_plural': 'verification codes'},
        ),
    ]
