version: "3.8"

services:
  web:
    container_name: drf-blog-api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: drf-blog-api-db
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_drf_dev
      - POSTGRES_PASSWORD=django_drf_dev
      - POSTGRES_DB=django_drf_dev_db

volumes:
  postgres_data: