SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = False

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = "None"

CRSF_COOKIE_SAMESITE = "None"
