# Generated by Django 3.2.1 on 2021-08-22 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersModel',
            new_name='Follower',
        ),
    ]
