# Generated by Django 3.2.1 on 2021-09-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'ordering': ('-banned_at',), 'verbose_name': 'ban', 'verbose_name_plural': 'bans'},
        ),
    ]
