# Generated by Django 3.1.7 on 2021-03-04 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followersmodel',
            name='follower_user',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followersmodel',
            name='following_user',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='followersmodel',
            unique_together={('follower_user', 'following_user')},
        ),
        migrations.RemoveField(
            model_name='followersmodel',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='followersmodel',
            name='follows',
        ),
    ]
